version: '3'

services:
  ngm:
    container_name: ngm 
    image: 'jc21/nginx-proxy-manager:latest' 
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
      # pihole
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 547:547/udp
      - 81:81
      - 8080:8080
      # plex
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      # wireguard
      - 51820:51820/udp
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      reverse-proxy:
        ipv4_address: 10.2.0.100

