version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.nucbox.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always
    networks:
      - private_network

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '5335:53/tcp'
      - '5335:53/udp'
      - "67:67/udp"
      - '8080:80/tcp'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      TZ: 'America/New_York'
      WEB_PASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_LOCAL_IPV4: 192.168.1.161
      PIHOLE_DNS_: 10.2.0.200 
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.nucbox.lan
      VIRTUAL_PORT: 80
    extra_hosts:
      # LAN hostnames for other docker containers using nginx-proxy
      - 'nucbox.lan:192.168.1.161'
      - 'pihole pihole.nucbox.lan:192.168.1.161'
      - 'plex plex.nucbox.lan:192.168.1.161'
      - 'transmission transmission.nucbox.lan:192.168.1.161'
      - 'portainer portainer.nucbox.lan:192.168.1.161'
    restart: always
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest 
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8234/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: 'America/New_York'
      VIRTUAL_HOST: plex.nucbox.lan
      VIRTUAL_PORT: 32400
      PLEX_UID: 1000
      PLEX_GID: 1000
      VERSION: latest
      PLEX_CLAIM: ${PLEX_CLAIM}
    hostname: nucbox
    volumes:
      - /media/nas/hdd1/plex/config:/config
      - /media/nas/hdd1/plex/transcode:/transcode
      - /media/nas/hdd1/transmission/Movies:/data/Movies
      - /media/nas/hdd1/transmission/TV:/data/TV
      - /media/nas/hdd1/transmission/Music:/data/Music
    networks:
      - private_network

  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SERVERPORT=51820
      - SERVERURL=kunginator.duckdns.org
      - PEERS=3 # How many peers to generate for you (clients)
      - PEERDNS=10.2.0.100
      - INTERNAL_SUBNET=10.6.0.0
      
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    networks:
      - private_network

  transmission-openvpn:
      container_name: transmission-openvpn
      cap_add:
          - NET_ADMIN
      volumes:
          - '/media/nas/hdd1/transmission:/data'
          - '/media/nas/hdd1/transmission/config/:/config'
          - '/vpn-configs-contrib/.git:/.git'
      environment:
        OPENVPN_PROVIDER: VPNUNLIMITED
        OPENVPN_CONFIG: ca-tr,fr,ro
        OPENVPN_USERNAME: ${OPENVPN_USERNAME}
        OPENVPN_PASSWORD: ${OPENVPN_PASSWORD} 
        LOCAL_NETWORK: 192.168.0.0/16,10.6.0.2/32
        TRANSMISSION_WEB_UI: combustion
        PROXY_LOCATION: transmission 
        VIRTUAL_HOST: transmission.nucbox.lan
        VIRTUAL_PORT: 9091
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      ports:
          - '9091:9091'
      image: haugene/transmission-openvpn:latest
      networks:
        - private_network
          
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    environment:
      PROXY_LOCATION: portainer
      VIRTUAL_HOST: portainer.nucbox.lan
      VIRTUAL_PORT: 9443
    ports:
      - 9443:9443
    networks:
      - private_network


