version: '3'

name: 'nucbox'

include:
  - path: 'pihole/unboundpiguard.yml'
  - path: 'ngm/ngm.yml'
  - path: 'plex/plex.yml'
  - path: 'transmission/transmission.yml'
  - path: 'portainer/portainer.yml'
  - path: 'commons.yml'

