version: "3"

secrets:
  duckdns_token:
    file: token.txt
      
services:
  duckdns:
    image: 'lscr.io/linuxserver/duckdns:latest'
    container_name: duckdns
    environment:
      TZ: America/New_York
      SUBDOMAINS: kunginator
      FILE__TOKEN: /run/secrets/duckdns_token
    restart: unless-stopped
    secrets:
      - duckdns_token
